api_key: 57143784-19ef-456b-94c9-ba68c8cb079b
api_path: /api
databases:
- label: default
  type: csv
  uri: /home/johan/Repositories/PHT/beweeghuis-pht/infrastructure/beta.csv
encryption:
  enabled: false
  private_key: ''
logging:
  backup_count: 5
  datefmt: '%Y-%m-%d %H:%M:%S'
  format: '%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s'
  level: DEBUG
  loggers:
  - level: warning
    name: urllib3
  - level: warning
    name: requests
  - level: warning
    name: engineio.client
  - level: warning
    name: docker.utils.config
  - level: warning
    name: docker.auth
  max_size: 1024
  use_console: true
port: '5000'
server_url: http://host.docker.internal
task_dir: ./beta/tasks